### ISSUE TITLE
Error in npm run review-code

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#401]
Not sure what I'm doing wrong, but I updated to master, removed node_modules,  npm install. I then run `npm run tests` and it "passed" but there were a bunch of errors. I then narrowed it down to `npm run review-code`.

Here is the command line and the first errors spewed:
```
$ npm run review-code

> alsatian@2.0.0-20170526 review-code /home/wink/prgs/alsatian.myfork
> tslint "./**/*.ts" --exclude "./**/*.d.ts" --exclude "./test/**/*.ts" --exclude "./node_modules/**/*.ts"


ERROR: cli/alsatian-cli-options.d.ts[3, 14]: The class property 'fileGlobs' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[5, 14]: The class property 'timeout' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[7, 14]: The class property 'tap' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[9, 14]: The class property 'versionRequested' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[11, 14]: The class property 'helpRequested' must be marked either 'priv
...
```
Here is the debug-log:
```
$ cat /home/wink/.npm/_logs/2017-06-01T15_44_02_126Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'review-code' ]
2 info using npm@4.6.1
3 info using node@v7.10.0
4 verbose run-script [ 'prereview-code', 'review-code', 'postreview-code' ]
5 info lifecycle alsatian@2.0.0-20170526~prereview-code: alsatian@2.0.0-20170526
6 silly lifecycle alsatian@2.0.0-20170526~prereview-code: no script for prereview-code, continuing
7 info lifecycle alsatian@2.0.0-20170526~review-code: alsatian@2.0.0-20170526
8 verbose lifecycle alsatian@2.0.0-20170526~review-code: unsafe-perm in lifecycle true
9 verbose lifecycle alsatian@2.0.0-20170526~review-code: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/wink/prgs/alsatian.myfork/node_modules/.bin:/home/wink/prgs/wabt.myfork/bin:/home/wink/foss/emscripten:./node_modules/.bin:/home/wink/.npm-global/bin:/home/wink/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/wink/foss/depot_tools
10 verbose lifecycle alsatian@2.0.0-20170526~review-code: CWD: /home/wink/prgs/alsatian.myfork
11 silly lifecycle alsatian@2.0.0-20170526~review-code: Args: [ '-c',
11 silly lifecycle   'tslint "./**/*.ts" --exclude "./**/*.d.ts" --exclude "./test/**/*.ts" --exclude "./node_modules/**/*.ts"' ]
12 silly lifecycle alsatian@2.0.0-20170526~review-code: Returned: code: 2  signal: null
13 info lifecycle alsatian@2.0.0-20170526~review-code: Failed to exec review-code script
14 verbose stack Error: alsatian@2.0.0-20170526 review-code: `tslint "./**/*.ts" --exclude "./**/*.d.ts" --exclude "./test/**/*.ts" --exclude "./node_modules/**/*.ts"`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid alsatian@2.0.0-20170526
16 verbose cwd /home/wink/prgs/alsatian.myfork
17 verbose Linux 4.11.3-1-ARCH
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "review-code"
19 verbose node v7.10.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 2
23 error alsatian@2.0.0-20170526 review-code: `tslint "./**/*.ts" --exclude "./**/*.d.ts" --exclude "./test/**/*.ts" --exclude "./node_modules/**/*.ts"`
23 error Exit status 2
24 error Failed at the alsatian@2.0.0-20170526 review-code script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by jamesrichford** [comment]
@winksaville looks like tslint is reviewing the `.d.ts` files despite being told to exclude them. Looks like tslint made a release 31 minutes ago so most likely it's to do with that as we had CI run a few hours ago fine.

**Comment by winksaville** [comment]
I rolled back to 5.3.2 and it worked, I'll create an issue on tslint site,
txs.

**Comment by winksaville** [comment]
tslint has a [fix being tested](https://github.com/palantir/tslint/pull/2858). As it turned out [tslint issue 2855](https://github.com/palantir/tslint/issues/2855) was reported just be mine.

**Comment by winksaville** [comment]
[tslint is now fixed](https://github.com/palantir/tslint/pull/2860), closing
