### ISSUE TITLE
Admit ts files as input

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#434]
Actually, if you call for example `alsatian ./src/**/*.spec.ts` it will throw an error because the code needs to be a `*.js` code. 

It would be nice if the alsatian supports *.ts files as input.

**Comment by jamesrichford** [comment]
Yes indeed this is something we want to do. However node as it stands doesn't support this as it needs the compiled javascript. We do have an example of how to do this with tsnode in #419 which is awesome because you can skip the compile step. However we want to make this a bit neater so it's easier to use similar to how you're noting above.

**Comment by jhm-ciberman** [comment]
It would be great to integrate tsnode inside alsatian then. 
Should we close this issue as duplicate then? Or left it opened?

**Comment by jamesrichford** [comment]
I think we can keep this one open to track a CLI option which I think was more what you were after?

**Comment by anodynos** [comment]
The example in #419 doesn't work anymore - I get: 

```
ERROR LOADING FILE: ../foo.spec.ts
.../foo.spec.ts:1
(function (exports, require, module, __filename, __dirname) { import * as _ from 'lodash';
                                                                    ^

SyntaxError: Unexpected token *
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/anodynos/.npm/_npx/25517/lib/node_modules/ts-node/src/index.ts:406:14)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)npm ERR! code ELIFECYCLE
```
I tried both:

    "test-runner": "ts-node -r ts-node/register src/test/alsatianTestRunner.ts",
    "test-runner2": "npx -p ts-node -p typescript ts-node src/test/alsatianTestRunner.ts",

and both ts-node@7 & ts-node@8 (using alsatian@2.3.0) 

Mentioned in #419 first, but here its better cause issue is open.
