### ISSUE TITLE
Error when using toEqual to compare null to object

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#500]
Using alsatian 2.3.0, this test:

```
@Test()
public foo() {
    Expect(null).toEqual({ a: 3 });
}
```

Gives me this error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at MixedMatcher.Matcher._checkObjectsAreDeepEqual (D:\Code\twotime\node_modules\alsatian\core\matchers\matcher.js:116:36)
    at MixedMatcher.Matcher.toEqual (D:\Code\twotime\node_modules\alsatian\core\matchers\matcher.js:60:31)
    at CreateNoteInformationTests.foo (D:\Code\twotime\bin-test\test\harvest\create-note-information.test.js:101:33)
    at TestItem._execute (D:\Code\twotime\node_modules\alsatian\core\running\test-item.js:130:58)
    at D:\Code\twotime\node_modules\alsatian\core\running\test-item.js:122:35
    at new Promise (<anonymous>)
    at TestItem.<anonymous> (D:\Code\twotime\node_modules\alsatian\core\running\test-item.js:112:39)
    at step (D:\Code\twotime\node_modules\alsatian\core\running\test-item.js:32:23)
    at Object.next (D:\Code\twotime\node_modules\alsatian\core\running\test-item.js:13:53)
```

**Comment by bartlomiejzuber** [comment]
I have the same problem when there's a null value inside of object with nested array.
```javascript
@Test()
public foo() {
    Expect(result).toEqual({
            a: [
                {
                    b: null,
                },
            ]
        });
}
```

Here's the stack:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at MixedMatcher.Matcher._checkObjectsAreDeepEqual (Q:\Repos\LetsShield\node_modules\alsatian\core\matchers\matcher.js:115:36)
    at MixedMatcher.Matcher._checkObjectsAreDeepEqual (Q:\Repos\LetsShield\node_modules\alsatian\core\matchers\matcher.js:128:26)
    at MixedMatcher.Matcher._checkObjectsAreDeepEqual (Q:\Repos\LetsShield\node_modules\alsatian\core\matchers\matcher.js:128:26)
    at MixedMatcher.Matcher._checkObjectsAreDeepEqual (Q:\Repos\LetsShield\node_modules\alsatian\core\matchers\matcher.js:128:26)
    at MixedMatcher.Matcher.toEqual (Q:\Repos\LetsShield\node_modules\alsatian\core\matchers\matcher.js:60:31)
    at GetFilteredQuestionAnswersTests.<anonymous> (Q:\Repos\LetsShield\src\functions\user\subscriptionPlans\get-subscription-plans.test.ts:125:24)
    at step (Q:\Repos\LetsShield\node_modules\tslib\tslib.js:133:27)
    at Object.next (Q:\Repos\LetsShield\node_modules\tslib\tslib.js:114:57)
    at fulfilled (Q:\Repos\LetsShield\node_modules\tslib\tslib.js:104:62)
```
