### ISSUE TITLE
value.split is not a function when test errors

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#544]
I get an error thrown from `buildObjectDiff` when my test fails in Alsatian 3.0.0. This doesn't happen in previous versions.

Here is my test:

```typescript
import { Test, Expect, TestFixture } from "alsatian";

@TestFixture()
export class FooTests {
    @Test()
    public test() {
        const expected = {
            price: 160,
            foo: "bar"
        };

        const result = {
            price: 159.99999999999997,
            foo: "bar"
        };

        Expect(result).toEqual(expected);
    }
}
```

And here is my output (in TAP format to rule out Tap Bark)

```
> alsatian foo.test.ts --tap

TAP version 13
1..1
# FIXTURE FooTests
not ok 1 FooTests > test
 ---
 message: The test threw an unhandled error.
 severity: fail
 data:
   got: an unhandled error
   expect: no unhandled errors to be thrown
   details:
     type: TypeError
     message: value.split is not a function
     stack: |-
       TypeError: value.split is not a function
           at Diff.split [as tokenize] (C:\Code\alsatian-test\node_modules\diff\src\diff\base.js:167:18)
           at Diff.tokenize [as diff] (C:\Code\alsatian-test\node_modules\diff\src\diff\base.js:27:39)
           at Object.diff [as diffChars] (C:\Code\alsatian-test\node_modules\diff\src\diff\character.js:4:75)
           at diffString (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:26:18)
           at stringifyDiffProp (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:92:45)
           at diffs.filter.map.diffItem (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:63:26)
           at Array.map (<anonymous>)
           at buildObjectDiff (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:63:10)
           at buildDiff (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:42:12)
           at Object.diff (C:\Code\alsatian-test\node_modules\alsatian\dist\core\matchers\diff.js:11:12)
 ...
```

**Comment by Jameskmonger** [comment]
The issue is passing non-string values into `diff.diffChars`

Maybe `toString()` in `stringifyDiffProp`?

**Comment by TGATM-Magnus** [comment]
I can confirm the issue - just run int it as well.

**Comment by TGATM-Magnus** [comment]
#547

**Comment by jamesadarich** [comment]
Published fix
