### ISSUE TITLE
Alsatian outputting failing tests multiple times

### ISSUE THREAD

**Issue by hisuwh** [alsatian-test/alsatian#605]
The latest version of Alsatian outputs failing tests multiple times.  Seems like its catching the error at different levels and reporting it every time:

For example here I have 5 failing tests but its reporting 56 failiures:

> It does not appear to present the same problem with --tap

```
 WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\code\Client.Application\Company.Application.Web\Scripts\src\ApplicationForm\Utils\application-form-keep-alive-ping.ts:11:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\src\ApplicationForm\Utils\application-form-keep-alive-ping.js:5:58)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

(node:22284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
  WARN: IgnoreTest has been deprecated and will be removed in version 4.0.0. Use the Ignore decorator instead.
  FAIL: DateRange > shouldShowErrorForEndDateIfCurrentIsSetToTrue
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: MarketingConsentQuestionTest > shouldSetAcceptToTrueIfApplicationSubmittedAndConsentAccepted
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: CandidateDetailsQuestionTests > shouldShowErrorIfNoGenderInitialised
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: ContactDetailsQuestionTests > shouldHaveErrorForCurrentUserEmailForNonApplicantUserWhenEmailAddressMandatoryForCustomerCases
   Expected objects to be equal

  diff:
  no differences
  FAIL: MaritalStatusQuestionTests > shouldShowErrorIfNoMaritalInitialised
   Expected false to be true.

  expected:
  true
  actual:
  false
  FAIL: NINumberQuestion > shouldEvaluateImmediateWhenReevaluateValidityCalled
   The test threw an unhandled error.

  type:
  TypeError

  message:
  toHaveBeenCalled requires value passed in to Expect to be a FunctionSpy or a spied on function.

  stack:
  TypeError: toHaveBeenCalled requires value passed in to Expect to be a FunctionSpy or a spied on function.
      at FunctionMatcher.toHaveBeenCalled (C:\code\Client.Application\Company.Application.Web\node_modules\alsatian\dist\core\matchers\function-matcher.js:46:19)
      at NINumberQuestionTests.<anonymous> (C:\code\Client.Application\Company.Application.Web\Scripts\test\ApplicationForm\Questions\NINumberQuestion.test.ts:207:73)
      at Generator.next (<anonymous>)
      at fulfilled (C:\code\Client.Application\Company.Application.Web\Scripts\test_build\test\ApplicationForm\Questions\NINumberQuestion.test.js:11:58)Pass: 763 / 769
  Fail: 6 / 769
  Ignore: 5 / 769
```

**Comment by jamesadarich** [comment]
I think this should now be resolved @hisuwh if not please feel free to reopen :)
