### ISSUE TITLE
toContain causes invalid output with array of objects

### ISSUE THREAD

**Issue by hisuwh** [alsatian-test/alsatian#646]
E.g.
```ts
const array = [];
Expect(array).toContain({});
```

Outputs:
```
100% complete
Warning: Failed prop type: Invalid prop `children` supplied to `Box`, expected a ReactNode.
    in Box (created by FailureDetail)
    in FailureDetail (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Static)
    in Static (created by TapBarkResults)
    in TapBarkResults (created by TapBarkRoot)
    in TapBarkRoot
    in App
The above error occurred in the <div> component:
    in div (created by Box)
    in Box (created by FailureDetail)
    in FailureDetail (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Static)
    in Static (created by TapBarkResults)
    in TapBarkResults (created by TapBarkRoot)
    in TapBarkRoot
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
(node:30660) UnhandledPromiseRejectionWarning: Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Box)
    in Box (created by FailureDetail)
    in FailureDetail (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Box)
    in Box (created by TapBarkResults)
    in div (created by Static)
    in Static (created by TapBarkResults)
    in TapBarkResults (created by TapBarkRoot)
    in TapBarkRoot
    in App
    at throwOnInvalidObjectType (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:4524:15)
    at reconcileChildFibers (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:5382:7)
    at reconcileChildren (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:7865:28)
    at updateHostComponent (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:8387:3)
    at beginWork$1 (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:9969:14)
    at Object.invokeGuardedCallbackImpl (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:11563:10)
    at invokeGuardedCallback (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:11740:31)
    at beginWork$$1 (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:15778:7)
    at performUnitOfWork (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:14696:12)
    at workLoopSync (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:14669:22)
    at performSyncWorkOnRoot (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:14265:11)
    at C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:1931:24
    at unstable_runWithPriority (C:\code\_personal\uwhtraining\node_modules\scheduler\cjs\scheduler.development.js:697:12)
    at runWithPriority (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:1881:10)
    at flushSyncCallbackQueueImpl (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:1926:7)
    at flushSyncCallbackQueue (C:\code\_personal\uwhtraining\node_modules\react-reconciler\cjs\react-reconciler.development.js:1914:3)
(node:30660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:30660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! Test failed.  See above for more details.
```

**Comment by hisuwh** [comment]
Presumably, you're doing something like:
```tsx
<Box>{expected}</Box>
```
Which will be invalid when expected is an object. Will need to stringify it or something.

**Comment by jamesadarich** [comment]
@Jameskmonger this one
