### ISSUE TITLE
Wiki stating example no longer works.

### ISSUE THREAD

**Issue by alexsmaliy** [alsatian-test/alsatian#684]
Alsatian 3.2.1

Basic setup:
```shell
npm install --global alsatian@latest
mkdir ./dummy
cd ./dummy
npm init --yes
cat << EOF > example.test.spec
import { Expect, Test } from "alsatian";

export class ExampleTestFixture {

  @Test()
  public exampleTest() {
    Expect(1 + 1).toBe(2);
  }
}
EOF
alsatian ./example.test.spec

```
Error:
```
ERROR LOADING FILE: /home/alex/code/dummy/example.test.spec
/home/alex/code/dummy/example.test.spec:1
import { Expect, Test } from "alsatian";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
    at TestLoader.loadTestFixture (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-loader.js:11:58)
    at /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:46:80
```

**Comment by jamesadarich** [comment]
This looks like you're using `esnext` as your module type for `typescript` but your version of node isn't set up for it. You can either enable esmodules for node or switch to `commonjs`.

I think this support is in node 13 but you have to enable it. Details can be found in node's docshttps://nodejs.org/api/esm.html#esm_ecmascript_modules

Let me know if this works for you or if you need any further help? :)

**Comment by alexsmaliy** [comment]
Hey @jamesadarich, thanks for responding! The example code is copied verbatim from the Alsatian wiki [here](https://github.com/alsatian-test/alsatian/wiki/test-structure).

If I name the example test file to have an `.mjs` extension, Alsatian CLI errors with
```
ERROR LOADING FILE: /home/alex/code/dummy/example.spec.mjs
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alex/code/dummy/example.spec.mjs
    at Module.load (internal/modules/cjs/loader.js:994:11)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
    at TestLoader.loadTestFixture (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-loader.js:11:58)
    at /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:46:80
    at Array.forEach (<anonymous>)
    at TestSet._loadTestFixtures (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:37:27)
    at TestSet.addTestsFromFiles (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:34:14)
```
If I add `"type": "module"` to `package.json`, Alsatian CLI errors with
```
ERROR LOADING FILE: /home/alex/code/dummy/example.spec.js
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alex/code/dummy/example.spec.js
require() of ES modules is not supported.
require() of /home/alex/code/dummy/example.spec.js from /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename example.spec.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/alex/code/dummy/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
    at TestLoader.loadTestFixture (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-loader.js:11:58)
    at /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:46:80
    at Array.forEach (<anonymous>)
    at TestSet._loadTestFixtures (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:37:27)
```
I should mention that I do have Alsatian unit tests running in some of my other projects, but only via `ts-node -r esm`. I filed this ticket because I'd like to get off of that and start using the Alsatian CLI.

**Comment by alexsmaliy** [comment]
Running the example code as a TypeScript file using Alsatian CLI results in this:
```ERROR LOADING FILE: /home/alex/code/dummy/example.spec.ts
TypeError: Cannot read property 'Expect' of undefined
    at Object.<anonymous> (/home/alex/code/dummy/example.spec.ts:3:9)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module.m._compile (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/node_modules/ts-node/src/index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/node_modules/ts-node/src/index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
```
And, finally, using the CLI on output produced by `tsc` with `"target": "es5"` and `"module": "commonjs"` also leads to errors, whether `"type": "module"` is set in `package.json` or not:
```
ERROR LOADING FILE: /home/alex/code/dummy/example.spec.js
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alex/code/dummy/example.spec.js
require() of ES modules is not supported.
require() of /home/alex/code/dummy/example.spec.js from /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename example.spec.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/alex/code/dummy/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
    at TestLoader.loadTestFixture (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-loader.js:11:58)
    at /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:46:80
    at Array.forEach (<anonymous>)
    at TestSet._loadTestFixtures (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:37:27)
```
```
ERROR LOADING FILE: /home/alex/code/dummy/example.spec.js
TypeError: Cannot read property 'Expect' of undefined
    at Object.<anonymous> (/home/alex/code/dummy/example.spec.js:13:33)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FileRequirer.require (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/file-requirer.js:5:16)
    at TestLoader.loadTestFixture (/home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-loader.js:11:58)
    at /home/alex/.nvm/versions/node/v13.12.0/lib/node_modules/alsatian/dist/core/test-set.js:46:80
```

**Comment by jamesadarich** [comment]
Ah OK then, looks like we may not have full support for esm as things stand. I'm going to change this issues name to reflect this if that's ok?

Is this a blocker for you or can you use commonks for now?

**Comment by alexsmaliy** [comment]
Since it looks like you folks are using ts-node, it's not clear if they ever solidified support for ES modules.

**Comment by jamesadarich** [comment]
Yes I think you're likely correct, may be worth seeing if there is at least a temporary work around with node 14 on the horizon and this becoming a more popular module system if we can't get support from ts-node.

**Comment by alexsmaliy** [comment]
No worries about the ticket! I have a workaround, I'm just bummed that the ecosystem support for modules is so spotty after a couple of years of availability.

**Comment by jamesadarich** [comment]
Yep, although I guess because of a combination of it being behind an experimental flag for most of that time and dependencies often having an impact on using functionality / backwards compatibility we can have awkward transitions sometimes.

I've added this to our next milestone though so this will get looked at. If you have some time and inclination I would gratefully received aPR for it :)

**Comment by alexsmaliy** [comment]
Might take a look at what it would take!

**Comment by mwgamble** [comment]
An easy solution to this problem is to install the `esm` package and require it on the command-line before doing anything else.

**Comment by jamesadarich** [comment]
Nice tip @mwgamble :) I'll give this a test with some other changes for 4.0.0 and add this as a recommendation with some props to you! 👍
